name: CI

on:
  pull_request:
    branches: [pipfile-experiment]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps from lockfile
        run: pipenv sync
      - name: Install package (editable)
        run: pipenv run pip install -e .
      - name: Test with pytest
        run: pipenv run pytest -q

# Remove deliver from feature branch as unique version code must be guaranteed
#   deliver:
#     needs: [build]
#     runs-on: ubuntu-latest
#     timeout-minutes: 5
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install Python, pipenv and Pipfile packages
#         uses: kojoru/prepare-pipenv@v1
#       - name: Build package
#         run: |
#           pipenv install build
#           pipenv run python -m build .
#       - name: Publish to PyPI test server
#         uses: pypa/gh-action-pypi-publish@release/v1
#         with:
#           password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#           repository-url: https://test.pypi.org/legacy/
